from datetime import date


TITULO_PRINCIPAL = 'ANÁLISE DA VARIAÇÃO DO PREÇO DO PETRÓLEO BRENT'
TITULO_INTRODUCAO = 'INÍCIO'
TITULO_HISTORIA = 'HISTÓRICO DO PREÇO'
TITULO_ANALISE_EXPLORATORIA = 'EXPLORANDO OS DADOS'
TITULO_MODELO = 'MODELO DE PREVISÃO'
TITULO_REFERENCIAS = 'REFERÊNCIAS'
DATA_INICIAL = date(2024, 7, 1)